# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c798d6e7bfa2b6ac99446dc0807666c51a08281505bf2fc6e7c03361e1d0dce6c437feef7a6b23ccd4b8e6296267cfa8d0ee62cfc7de3aff79e77de69b20182f

test:
  secret_key_base: b6d4ec86b20f2e491941021e5959521edf8e6114b7171a5f0e5b2edbf8ced94fb832ee65dfee89d4732cafc6e3128d22caae4f663515c6c21296d4c49a0ba2d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
